const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const User = require('../models/User');
const Category = require('../models/Category');
const Product = require('../models/Product');
const Review = require('../models/Review');
const Order = require('../models/Order');
const Cart = require('../models/Cart');

const connectDB = async () => {
  const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/shopsphere';
  try {
    await mongoose.connect(uri, { serverSelectionTimeoutMS: 3000 });
    return;
  } catch (err) {
    console.log('Local MongoDB not accessible directly. Starting embedded MongoDB engine...');
    const { MongoMemoryServer } = require('mongodb-memory-server');
    const mongod = await MongoMemoryServer.create({
      instance: { dbName: 'shopsphere', port: 27017 },
    }).catch(async () => {
      return await MongoMemoryServer.create({ instance: { dbName: 'shopsphere' } });
    });
    const memoryUri = mongod.getUri();
    await mongoose.connect(memoryUri);
    console.log(`Connected to fallback embedded MongoDB at ${memoryUri}`);
  }
};

const seedData = async (shouldExit = true) => {
  try {
    await connectDB();

    // Clear existing data
    await Promise.all([
      Category.deleteMany({}),
      User.deleteMany({}),
      Product.deleteMany({}),
      Review.deleteMany({}),
      Order.deleteMany({}),
      Cart.deleteMany({}),
    ]);

    // 1. Create 10 Categories
    const categoriesData = [
      {
        name: 'Electronics',
        description: 'Latest electronic gadgets, smart devices, and home tech',
        image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Mobile Phones',
        description: 'Premium smartphones, flagship devices, and mobile accessories',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Laptops',
        description: 'Powerful workstations, ultrabooks, and high-performance gaming laptops',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Headphones',
        description: 'High-fidelity audio, wireless earbuds, and noise-cancelling headphones',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Cameras',
        description: 'Professional DSLRs, mirrorless cameras, lenses, and action cams',
        image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: "Men's Clothing",
        description: 'Stylish apparel, casual wear, jackets, and formal attire for men',
        image: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: "Women's Clothing",
        description: 'Elegant dresses, everyday essentials, outerwear, and fashionwear',
        image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Shoes',
        description: 'Athletic sneakers, running shoes, casual footwear, and leather boots',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Home & Kitchen',
        description: 'Modern cookware, smart appliances, espresso machines, and home decor',
        image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      },
      {
        name: 'Books',
        description: 'Bestselling literature, programming guides, self-improvement, and novels',
        image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
      },
    ];

    const createdCategories = await Category.insertMany(categoriesData);

    // Create Category lookup map
    const catMap = {};
    createdCategories.forEach((cat) => {
      catMap[cat.name] = cat._id;
    });

    // 2. Create 1 Admin & 10 Customers (11 Users)
    const adminSalt = await bcrypt.genSalt(10);
    const adminPassword = await bcrypt.hash('Admin@123', adminSalt);

    const customerSalt = await bcrypt.genSalt(10);
    const customerPassword = await bcrypt.hash('Password@123', customerSalt);

    const usersData = [
      {
        name: 'Admin ShopSphere',
        email: 'admin@shopsphere.com',
        password: adminPassword,
        phone: '+1 555-0100',
        role: 'ADMIN',
        address: { address: '100 Tech Blvd, Suite 400', city: 'San Jose', state: 'CA', pincode: '95113' },
      },
      {
        name: 'John Doe',
        email: 'john@example.com',
        password: customerPassword,
        phone: '+1 555-0101',
        role: 'CUSTOMER',
        address: { address: '742 Evergreen Terrace', city: 'Springfield', state: 'IL', pincode: '62704' },
      },
      {
        name: 'Jane Smith',
        email: 'jane@example.com',
        password: customerPassword,
        phone: '+1 555-0102',
        role: 'CUSTOMER',
        address: { address: '124 Conch Street', city: 'Bikini Bottom', state: 'HI', pincode: '96815' },
      },
      {
        name: 'Michael Johnson',
        email: 'michael@example.com',
        password: customerPassword,
        phone: '+1 555-0103',
        role: 'CUSTOMER',
        address: { address: '42 Wallaby Way', city: 'Sydney', state: 'NY', pincode: '10001' },
      },
      {
        name: 'Emily Davis',
        email: 'emily@example.com',
        password: customerPassword,
        phone: '+1 555-0104',
        role: 'CUSTOMER',
        address: { address: '221B Baker Street', city: 'Marylebone', state: 'CA', pincode: '90001' },
      },
      {
        name: 'David Brown',
        email: 'david@example.com',
        password: customerPassword,
        phone: '+1 555-0105',
        role: 'CUSTOMER',
        address: { address: '350 Fifth Avenue', city: 'New York', state: 'NY', pincode: '10118' },
      },
      {
        name: 'Sarah Wilson',
        email: 'sarah@example.com',
        password: customerPassword,
        phone: '+1 555-0106',
        role: 'CUSTOMER',
        address: { address: '1600 Amphitheatre Pkwy', city: 'Mountain View', state: 'CA', pincode: '94043' },
      },
      {
        name: 'James Taylor',
        email: 'james@example.com',
        password: customerPassword,
        phone: '+1 555-0107',
        role: 'CUSTOMER',
        address: { address: '1 Infinite Loop', city: 'Cupertino', state: 'CA', pincode: '95014' },
      },
      {
        name: 'Olivia Anderson',
        email: 'olivia@example.com',
        password: customerPassword,
        phone: '+1 555-0108',
        role: 'CUSTOMER',
        address: { address: '410 Terry Ave N', city: 'Seattle', state: 'WA', pincode: '98109' },
      },
      {
        name: 'Robert Martinez',
        email: 'robert@example.com',
        password: customerPassword,
        phone: '+1 555-0109',
        role: 'CUSTOMER',
        address: { address: '500 S Buena Vista St', city: 'Burbank', state: 'CA', pincode: '91521' },
      },
      {
        name: 'Sophia Thomas',
        email: 'sophia@example.com',
        password: customerPassword,
        phone: '+1 555-0110',
        role: 'CUSTOMER',
        address: { address: '77 Massachusetts Ave', city: 'Cambridge', state: 'MA', pincode: '02139' },
      },
    ];

    const createdUsers = await User.insertMany(usersData);
    const customers = createdUsers.filter((u) => u.role === 'CUSTOMER');

    // 3. Create 100 Realistic Products (10 per category)
    const rawProducts = [
      // Electronics (10)
      {
        name: 'Samsung 55-Inch Crystal 4K UHD Smart TV',
        description: 'Dynamic Crystal Color delivers life-like variations so you can see every subtlety. Crystal Processor 4K upscale content to stunning clarity.',
        price: 499.99,
        discountPrice: 449.99,
        brand: 'Samsung',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=80',
        stock: 25,
        rating: 4.6,
        isFeatured: true,
      },
      {
        name: 'Anker Magnetic Wireless Charging Pad',
        description: 'Fast 15W magnetic inductive charging pad compatible with iPhone MagSafe and Qi-certified wireless devices.',
        price: 29.99,
        discountPrice: 24.99,
        brand: 'Anker',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1586816879360-004f5b0c51e5?auto=format&fit=crop&w=600&q=80',
        stock: 50,
        rating: 4.4,
        isFeatured: false,
      },
      {
        name: 'Nebula Capsule 3 Laser Mini Projector',
        description: 'Pocket-sized outdoor projector with 300 ANSI Lumens, 1080p Laser display, built-in battery, and Android TV 11.0.',
        price: 699.99,
        discountPrice: 629.99,
        brand: 'Anker',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80',
        stock: 15,
        rating: 4.7,
        isFeatured: true,
      },
      {
        name: 'Apple Watch Series 9 GPS 45mm',
        description: 'Powerful S9 SiP chip, double tap gesture, brighter display, and advanced health sensors for blood oxygen and ECG tracking.',
        price: 429.99,
        discountPrice: 399.99,
        brand: 'Apple',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80',
        stock: 30,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: 'Amazon Echo Dot 5th Gen Smart Speaker',
        description: 'Vibrant sound with Alexa voice control, smart home motion detection, and built-in temperature sensor.',
        price: 49.99,
        discountPrice: 39.99,
        brand: 'Amazon',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1543512214-318c7553f230?auto=format&fit=crop&w=600&q=80',
        stock: 80,
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'Belkin 3-in-1 MagSafe Fast Wireless Charger',
        description: 'Charge your iPhone, Apple Watch, and AirPods simultaneously with official 15W MagSafe high-speed charging.',
        price: 149.99,
        discountPrice: 129.99,
        brand: 'Belkin',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1622445262464-84b1456045b6?auto=format&fit=crop&w=600&q=80',
        stock: 6, // Low stock for dashboard alert
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'DJI Mini 4 Pro Drone with RC-2',
        description: 'Sub-249g lightweight camera drone with 4K/60fps HDR video, omnidirectional obstacle sensing, and 34-min flight time.',
        price: 759.99,
        discountPrice: 719.99,
        brand: 'DJI',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80',
        stock: 12,
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'Logitech MX Mechanical Wireless Keyboard',
        description: 'Low profile tactile quiet mechanical switches, dual-color keycaps, smart backlighting, and multi-device pairing.',
        price: 169.99,
        discountPrice: 149.99,
        brand: 'Logitech',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
        stock: 22,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'Razer DeathAdder V3 Pro Wireless Gaming Mouse',
        description: 'Ultra-lightweight 63g ergonomic design with Focus Pro 30K Optical Sensor and Gen-3 optical mouse switches.',
        price: 149.99,
        discountPrice: 129.99,
        brand: 'Razer',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
        stock: 18,
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'SanDisk 2TB Extreme Portable SSD',
        description: 'Rugged NVMe solid state drive with up to 1050MB/s read speeds, IP55 water and dust resistance.',
        price: 189.99,
        discountPrice: 159.99,
        brand: 'SanDisk',
        category: catMap['Electronics'],
        image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80',
        stock: 4, // Low stock for dashboard alert
        rating: 4.8,
        isFeatured: false,
      },

      // Mobile Phones (10)
      {
        name: 'Apple iPhone 15 Pro 256GB Titanium',
        description: 'Forged in titanium with aerospace-grade strength, revolutionary A17 Pro chip, customizable Action button, and 48MP camera system.',
        price: 1099.99,
        discountPrice: 999.99,
        brand: 'Apple',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80',
        stock: 20,
        rating: 4.9,
        isFeatured: true,
      },
      {
        name: 'Samsung Galaxy S24 Ultra 512GB',
        description: 'Galaxy AI smartphone with titanium exterior, embedded S Pen, 200MP camera with Quad Telephoto system, and Snapdragon 8 Gen 3.',
        price: 1299.99,
        discountPrice: 1199.99,
        brand: 'Samsung',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80',
        stock: 18,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: 'Google Pixel 8 Pro 128GB Obsidian',
        description: 'The pro phone engineered by Google with Google Tensor G3, advanced AI photo editing, and 24+ hour battery life.',
        price: 999.99,
        discountPrice: 849.99,
        brand: 'Google',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80',
        stock: 14,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'OnePlus 12 256GB Emerald Green',
        description: 'Snapdragon 8 Gen 3 flagship with 4th Gen Hasselblad Camera system, 2K 120Hz ProXDR display, and 100W SUPERVOOC charging.',
        price: 799.99,
        discountPrice: 749.99,
        brand: 'OnePlus',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80',
        stock: 22,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'Samsung Galaxy A54 5G 128GB',
        description: 'Awesome design with premium glass finish, Super AMOLED 120Hz screen, and optical image stabilization on the 50MP camera.',
        price: 449.99,
        discountPrice: 379.99,
        brand: 'Samsung',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=600&q=80',
        stock: 45,
        rating: 4.4,
        isFeatured: false,
      },
      {
        name: 'Apple iPhone 13 128GB Midnight',
        description: 'Super Retina XDR OLED display, cinematic mode in 1080p at 30 fps, and blazing-fast A15 Bionic chip.',
        price: 599.99,
        discountPrice: 549.99,
        brand: 'Apple',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80',
        stock: 35,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'Xiaomi 13 Pro 256GB Ceramic Black',
        description: 'Leica professional optical 1-inch sensor, Snapdragon 8 Gen 2, 120W HyperCharge, and 120Hz WQHD+ AMOLED.',
        price: 899.99,
        discountPrice: 799.99,
        brand: 'Xiaomi',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?auto=format&fit=crop&w=600&q=80',
        stock: 16,
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'Nothing Phone (2) 256GB Dark Grey',
        description: 'Iconic Glyph Interface with customized LED light sequences, dual 50MP cameras, and clean Nothing OS 2.0.',
        price: 699.99,
        discountPrice: 599.99,
        brand: 'Nothing',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=600&q=80',
        stock: 7, // Low stock
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'Motorola Razr+ Flip Smartphone',
        description: 'Large 3.6-inch external interactive display, ultra-smooth 165Hz folding OLED screen, and versatile Flex View hinge.',
        price: 999.99,
        discountPrice: 899.99,
        brand: 'Motorola',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?auto=format&fit=crop&w=600&q=80',
        stock: 11,
        rating: 4.3,
        isFeatured: false,
      },
      {
        name: 'ASUS ROG Phone 8 Pro Gaming Phone',
        description: 'Gaming powerhouse with AniMe Vision mini-LED rear display, AirTrigger ultrasonic controls, and 165Hz AMOLED.',
        price: 1199.99,
        discountPrice: 1099.99,
        brand: 'ASUS',
        category: catMap['Mobile Phones'],
        image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=80',
        stock: 8, // Low stock
        rating: 4.8,
        isFeatured: false,
      },

      // Laptops (10)
      {
        name: 'Apple MacBook Pro 14 M3 Pro 512GB',
        description: 'Liquid Retina XDR display, M3 Pro chip with 11-core CPU and 14-core GPU, up to 18 hours of battery life, Space Black finish.',
        price: 1999.99,
        discountPrice: 1849.99,
        brand: 'Apple',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80',
        stock: 12,
        rating: 4.9,
        isFeatured: true,
      },
      {
        name: 'Dell XPS 15 OLED Touch Laptop',
        description: '15.6-inch 3.5K OLED InfinityEdge touch display, Intel Core i7-13700H, NVIDIA GeForce RTX 4060, 32GB RAM, 1TB SSD.',
        price: 2199.99,
        discountPrice: 1999.99,
        brand: 'Dell',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=600&q=80',
        stock: 10,
        rating: 4.7,
        isFeatured: true,
      },
      {
        name: 'Lenovo ThinkPad X1 Carbon Gen 11',
        description: 'Ultralight carbon fiber business ultrabook with 14-inch 2.8K OLED screen, Intel Core i7, 16GB RAM, and legendary ThinkPad keyboard.',
        price: 1649.99,
        discountPrice: 1499.99,
        brand: 'Lenovo',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=600&q=80',
        stock: 15,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'ASUS ROG Zephyrus G14 Gaming Laptop',
        description: 'AMD Ryzen 9 8945HS, NVIDIA GeForce RTX 4070, 3K 120Hz OLED display in a thin CNC aluminum chassis.',
        price: 1999.99,
        discountPrice: 1799.99,
        brand: 'ASUS',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80',
        stock: 9, // Low stock
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'Apple MacBook Air 13 M2 256GB',
        description: 'Strikingly thin design in Starlight aluminum, 13.6-inch Liquid Retina display, MagSafe charging, and silent fanless operation.',
        price: 999.99,
        discountPrice: 899.99,
        brand: 'Apple',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=600&q=80',
        stock: 28,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'HP Spectre x360 2-in-1 14T Laptop',
        description: 'Convertible touchscreen with Intel Core Ultra 7 processor, 2.8K OLED display, 9MP webcam with AI framing, and stylus pen included.',
        price: 1599.99,
        discountPrice: 1399.99,
        brand: 'HP',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
        stock: 14,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'Acer Swift Go 14 OLED Laptop',
        description: 'Budget-friendly premium ultraportable featuring vibrant 2.8K 90Hz OLED, Intel Core i5, 16GB LPDDR5, and 512GB NVMe.',
        price: 799.99,
        discountPrice: 699.99,
        brand: 'Acer',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=600&q=80',
        stock: 20,
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'Microsoft Surface Laptop 5 13.5-Inch',
        description: 'Sleek PixelSense touchscreen, Alcantara or metal palm rest, Thunderbolt 4 connectivity, and all-day battery life.',
        price: 1299.99,
        discountPrice: 1099.99,
        brand: 'Microsoft',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1587614382346-4ec70e388b28?auto=format&fit=crop&w=600&q=80',
        stock: 16,
        rating: 4.4,
        isFeatured: false,
      },
      {
        name: 'Razer Blade 16 Dual-Mode Mini-LED',
        description: 'Desktop-grade gaming laptop with Intel Core i9-14900HX, RTX 4080, and revolutionary dual-mode UHD+ 120Hz / FHD+ 240Hz screen.',
        price: 3299.99,
        discountPrice: 2999.99,
        brand: 'Razer',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=600&q=80',
        stock: 5, // Low stock
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'Lenovo Legion Pro 5i Gen 9 Gaming Laptop',
        description: 'Esports calibrated 16-inch WQXGA 240Hz display, Intel Core i7-14700HX, RTX 4070, and ColdFront 5.0 cooling.',
        price: 1699.99,
        discountPrice: 1499.99,
        brand: 'Lenovo',
        category: catMap['Laptops'],
        image: 'https://images.unsplash.com/photo-1588797389471-315b89d78044?auto=format&fit=crop&w=600&q=80',
        stock: 18,
        rating: 4.7,
        isFeatured: false,
      },

      // Headphones (10)
      {
        name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
        description: 'Industry-leading noise cancelation with two processors and 8 microphones, ultra-comfortable lightweight design, and 30-hour battery life.',
        price: 399.99,
        discountPrice: 349.99,
        brand: 'Sony',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
        stock: 35,
        rating: 4.9,
        isFeatured: true,
      },
      {
        name: 'Bose QuietComfort Ultra Wireless Headphones',
        description: 'World-class noise cancellation, breakthrough spatialized audio, custom tune technology, and luxe design in Black.',
        price: 429.99,
        discountPrice: 379.99,
        brand: 'Bose',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
        stock: 22,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: 'Apple AirPods Pro 2nd Gen USB-C',
        description: 'Up to 2x more Active Noise Cancellation, Adaptive Audio, Personalized Spatial Audio, and MagSafe charging case with speaker.',
        price: 249.99,
        discountPrice: 199.99,
        brand: 'Apple',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=600&q=80',
        stock: 60,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'Sennheiser Momentum 4 Wireless',
        description: 'Audiophile-inspired 42mm transducer system, adaptive noise cancellation, and unprecedented 60-hour battery life.',
        price: 379.99,
        discountPrice: 299.99,
        brand: 'Sennheiser',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=600&q=80',
        stock: 19,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'Sony WF-1000XM5 True Wireless Earbuds',
        description: 'The best true wireless noise-cancelling earbuds with high-resolution audio wireless LDAC, bone conduction sensors, and AI noise reduction.',
        price: 299.99,
        discountPrice: 249.99,
        brand: 'Sony',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
        stock: 25,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'Beats Studio Pro Wireless Over-Ear',
        description: 'Custom acoustic platform with lossless audio via USB-C, Personalized Spatial Audio with dynamic head tracking, and up to 40 hours playtime.',
        price: 349.99,
        discountPrice: 249.99,
        brand: 'Beats',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1577174881658-0f30ed549adc?auto=format&fit=crop&w=600&q=80',
        stock: 30,
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'Audio-Technica ATH-M50x Professional Monitor Headphones',
        description: 'Critically acclaimed studio monitor headphones with 45mm large-aperture drivers and 90-degree swiveling earcups.',
        price: 169.99,
        discountPrice: 149.99,
        brand: 'Audio-Technica',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=600&q=80',
        stock: 40,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'JBL Tune 760NC Wireless Over-Ear',
        description: 'Active Noise Cancelling with JBL Pure Bass Sound, lightweight foldable design, multi-point connection, and 35H battery life.',
        price: 129.99,
        discountPrice: 99.99,
        brand: 'JBL',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?auto=format&fit=crop&w=600&q=80',
        stock: 48,
        rating: 4.3,
        isFeatured: false,
      },
      {
        name: 'Marshall Major IV On-Ear Bluetooth Headphones',
        description: 'Iconic Marshall vintage styling with custom tuned dynamic drivers, 80+ solid hours of wireless playtime, and wireless charging support.',
        price: 149.99,
        discountPrice: 129.99,
        brand: 'Marshall',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=600&q=80',
        stock: 8, // Low stock
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'Shure AONIC 50 Gen 2 Premium Studio Headphones',
        description: 'High-definition studio-quality sound with 50mm custom drivers, customizable spatial audio modes, and Snapdragon Sound technology.',
        price: 349.99,
        discountPrice: 299.99,
        brand: 'Shure',
        category: catMap['Headphones'],
        image: 'https://images.unsplash.com/photo-1545127398-14699f92334b?auto=format&fit=crop&w=600&q=80',
        stock: 5, // Low stock
        rating: 4.7,
        isFeatured: false,
      },

      // Cameras (10)
      {
        name: 'Canon EOS R50 Mirrorless Camera with 18-45mm Lens',
        description: 'Compact, lightweight mirrorless camera with 24.2MP APS-C sensor, Dual Pixel CMOS AF II, and uncropped 4K 30p movie recording.',
        price: 799.99,
        discountPrice: 749.99,
        brand: 'Canon',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80',
        stock: 14,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: 'Sony Alpha 7 IV Full-Frame Mirrorless',
        description: '33MP full-frame Exmor R sensor, BIONZ XR processing, real-time eye AF for humans, animals, and birds, 4K 60p 10-bit video.',
        price: 2499.99,
        discountPrice: 2299.99,
        brand: 'Sony',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80',
        stock: 10,
        rating: 4.9,
        isFeatured: true,
      },
      {
        name: 'Fujifilm X-T5 Mirrorless Camera Body',
        description: 'Retro mechanical dial design with fifth-generation 40.2MP X-Trans CMOS 5 HR sensor and 7 stops of internal image stabilization.',
        price: 1699.99,
        discountPrice: 1599.99,
        brand: 'Fujifilm',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=600&q=80',
        stock: 8, // Low stock
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'Nikon Z fc Mirrorless with 16-50mm Lens',
        description: 'Classic heritage styling inspired by the iconic Nikon FM2 film camera with 20.9MP DX sensor and 4K UHD vlogging support.',
        price: 1099.99,
        discountPrice: 999.99,
        brand: 'Nikon',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=600&q=80',
        stock: 12,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'GoPro HERO12 Black Action Camera',
        description: 'Rugged and waterproof to 33ft, 5.3K60 video recording, HyperSmooth 6.0 video stabilization, and HDR video and photo capabilities.',
        price: 399.99,
        discountPrice: 349.99,
        brand: 'GoPro',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80',
        stock: 35,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'DJI Osmo Pocket 3 Gimbal Camera',
        description: 'Pocket-sized stabilizer with 1-inch CMOS sensor, 4K/120fps recording, 2-inch rotatable OLED touchscreen, and full-pixel fast focus.',
        price: 519.99,
        discountPrice: 479.99,
        brand: 'DJI',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
        stock: 16,
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'Canon PowerShot G7 X Mark III Digital Camera',
        description: 'Compact vlogging powerhouse with 20.1MP 1-inch sensor, 4.2x optical zoom f/1.8-2.8 lens, and live YouTube streaming support.',
        price: 749.99,
        discountPrice: 699.99,
        brand: 'Canon',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
        stock: 6, // Low stock
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'Insta360 X3 Waterproof 360 Action Camera',
        description: 'Dual 1/2-inch 48MP sensors capturing 5.7K 360-degree video with FlowState stabilization and invisible selfie stick effect.',
        price: 449.99,
        discountPrice: 399.99,
        brand: 'Insta360',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=600&q=80',
        stock: 22,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'Sigma 24-70mm f/2.8 DG DN Art Lens',
        description: 'Standard zoom lens for full-frame mirrorless cameras offering extraordinary resolution throughout the entire zoom range.',
        price: 1099.99,
        discountPrice: 999.99,
        brand: 'Sigma',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1617005082133-548c4dd27f35?auto=format&fit=crop&w=600&q=80',
        stock: 15,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'Peak Design Everyday Backpack 20L v2',
        description: 'Award-winning versatile camera and laptop backpack with MagLatch hardware, weatherproof zippers, and customizable FlexFold dividers.',
        price: 279.99,
        discountPrice: 249.99,
        brand: 'Peak Design',
        category: catMap['Cameras'],
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
        stock: 20,
        rating: 4.9,
        isFeatured: false,
      },

      // Men's Clothing (10)
      {
        name: "Levi's Men's Sherpa Trucker Denim Jacket",
        description: 'A cozy take on the iconic original trucker jacket, lined with plush sherpa for warmth with signature metal shank buttons.',
        price: 128.00,
        discountPrice: 98.00,
        brand: "Levi's",
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80',
        stock: 30,
        rating: 4.7,
        isFeatured: true,
      },
      {
        name: 'Patagonia Better Sweater Fleece Quarter-Zip',
        description: 'Warm, 100% recycled polyester fleece jacket dyed with a low-impact process that significantly reduces dyestuff and water usage.',
        price: 139.00,
        discountPrice: 119.00,
        brand: 'Patagonia',
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
        stock: 25,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: "Carhartt WIP Men's Hooded Chase Sweatshirt",
        description: 'Heavyweight cotton-poly jersey fabric brushed for fleece-like backing, kangaroo pocket, and subtle Carhartt logo embroidery.',
        price: 115.00,
        discountPrice: 95.00,
        brand: 'Carhartt',
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80',
        stock: 35,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: "Men's Slim-Fit Stretch Oxford Shirt",
        description: 'Classic button-down collar constructed from durable 100% breathable organic cotton with slight stretch for mobility.',
        price: 69.50,
        discountPrice: 49.50,
        brand: 'J.Crew',
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80',
        stock: 45,
        rating: 4.4,
        isFeatured: false,
      },
      {
        name: 'The North Face 1996 Retro Nuptse Down Jacket',
        description: 'Iconic boxy silhouette with original shiny ripstop fabric and oversized baffles stuffed with 700-fill goose down.',
        price: 330.00,
        discountPrice: 299.00,
        brand: 'The North Face',
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=600&q=80',
        stock: 9, // Low stock
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: "Lululemon ABC Classic-Fit Pant 32L",
        description: 'Comfortable everyday trousers engineered with Warpstreme fabric for four-way stretch, shape retention, and wrinkle resistance.',
        price: 128.00,
        discountPrice: 110.00,
        brand: 'Lululemon',
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=600&q=80',
        stock: 28,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: "Champion Reverse Weave Heavyweight Crewneck",
        description: 'Legendary athletic crewneck engineered with signature vertical stretch reduction and heavy ribbed side panels.',
        price: 65.00,
        discountPrice: 49.99,
        brand: 'Champion',
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=600&q=80',
        stock: 50,
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: "Men's Tailored Merino Wool Blazer",
        description: 'Versatile Italian merino wool suit jacket with natural stretch, notch lapels, and breathable half-canvas construction.',
        price: 298.00,
        discountPrice: 249.00,
        brand: 'Banana Republic',
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
        stock: 14,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: "Barbour Classic Bedale Waxed Cotton Jacket",
        description: 'Authentic British heritage outerwear with thornproof waxed cotton, corduroy collar, and double zip storm fly.',
        price: 395.00,
        discountPrice: 345.00,
        brand: 'Barbour',
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
        stock: 7, // Low stock
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'Tommy Hilfiger Classic Pique Polo Shirt',
        description: 'Breathable pure cotton pique with contrast signature tipping on collar and embroidered flag emblem on the chest.',
        price: 59.50,
        discountPrice: 44.50,
        brand: 'Tommy Hilfiger',
        category: catMap["Men's Clothing"],
        image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80',
        stock: 40,
        rating: 4.3,
        isFeatured: false,
      },

      // Women's Clothing (10)
      {
        name: 'Aritzia The Super Puff Mid Goose Down Jacket',
        description: 'Engineered to keep you warm down to -30°C (-22°F), filled with 100% responsibly sourced 700+ fill-power goose down.',
        price: 325.00,
        discountPrice: 295.00,
        brand: 'Aritzia',
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
        stock: 16,
        rating: 4.9,
        isFeatured: true,
      },
      {
        name: 'Reformation Twilight Sleeveless Floral Midi Dress',
        description: 'Georgette fabric featuring a sweetheart neckline, fitted bodice with tie straps, and high side slit for flowing grace.',
        price: 278.00,
        discountPrice: 248.00,
        brand: 'Reformation',
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=600&q=80',
        stock: 18,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: "Everlane The Cashmere Crewneck Sweater",
        description: 'Luxuriously soft certified Grade-A Mongolian cashmere with ribbed cuffs and hem, relaxed modern silhouette.',
        price: 158.00,
        discountPrice: 128.00,
        brand: 'Everlane',
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=600&q=80',
        stock: 24,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: "Levi's Women's Ribcage Straight Ankle Jeans",
        description: "Levi's highest high rise with a classic straight leg, waist-defining fit, and authentic rigid denim construction.",
        price: 108.00,
        discountPrice: 79.99,
        brand: "Levi's",
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80',
        stock: 35,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'Lululemon Align High-Rise Yoga Pant 25"',
        description: 'Buttery-soft weightless Nulu fabric engineered for yoga with four-way stretch, sweat-wicking, and hidden waistband pocket.',
        price: 98.00,
        discountPrice: 88.00,
        brand: 'Lululemon',
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1506152983158-b4a74a01c721?auto=format&fit=crop&w=600&q=80',
        stock: 45,
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'Zara Double-Breasted Oversized Wool Blazer',
        description: 'Sharp lapel collar, structured shoulder pads, front flap pockets, and tailored double-breasted button fastening.',
        price: 129.00,
        discountPrice: 99.00,
        brand: 'Zara',
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80',
        stock: 20,
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'Madewell The Perfect Vintage Wide-Leg Crop Pant',
        description: 'High-fitted waist with easy wide legs, crafted from lightweight breathable garment-dyed cotton twill.',
        price: 98.00,
        discountPrice: 74.50,
        brand: 'Madewell',
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
        stock: 19,
        rating: 4.4,
        isFeatured: false,
      },
      {
        name: 'Mango Textured Wrap Trench Coat',
        description: 'Timeless double-breasted longline trench with tie belt, storm flap, wrist buckles, and waterproof coating.',
        price: 199.99,
        discountPrice: 159.99,
        brand: 'Mango',
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=80',
        stock: 8, // Low stock
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'Free People Easy Street Oversized Tunic',
        description: 'Slouchy, cozy oversized knit sweater with ribbed mock neck, dropped shoulders, and side slits.',
        price: 128.00,
        discountPrice: 98.00,
        brand: 'Free People',
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=600&q=80',
        stock: 22,
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'Cos Pure Silk Slip Maxi Skirt',
        description: 'Bias-cut fluid mulberry silk skirt that drapes effortlessly across the hips, finished with an elasticated waistband.',
        price: 175.00,
        discountPrice: 145.00,
        brand: 'COS',
        category: catMap["Women's Clothing"],
        image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=600&q=80',
        stock: 6, // Low stock
        rating: 4.8,
        isFeatured: false,
      },

      // Shoes (10)
      {
        name: 'Nike Air Max 270 Running Shoes',
        description: "Nike's biggest heel Air unit yet delivers ultra-soft cushioning that feels as impossible as it looks, lightweight mesh upper.",
        price: 160.00,
        discountPrice: 139.99,
        brand: 'Nike',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
        stock: 40,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: 'Adidas Ultraboost Light Running Shoes',
        description: 'Experience epic energy return with the lightest BOOST midsole ever engineered by Adidas, Continental Rubber outsole.',
        price: 190.00,
        discountPrice: 159.99,
        brand: 'Adidas',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80',
        stock: 35,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: 'New Balance 990v6 Made in USA',
        description: 'The pinnacle of heritage craftsmanship, featuring FuelCell foam cushioning and ENCAP midsole support in iconic grey suede.',
        price: 199.99,
        discountPrice: 184.99,
        brand: 'New Balance',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=600&q=80',
        stock: 25,
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'Dr. Martens 1460 8-Eye Smooth Leather Boot',
        description: 'The quintessential British work boot featuring grooved edges, yellow welt stitching, and comfortable air-cushioned sole.',
        price: 170.00,
        discountPrice: 149.00,
        brand: 'Dr. Martens',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=600&q=80',
        stock: 30,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'Birkenstock Arizona Birko-Flor Sandals',
        description: 'Timeless two-strap design with legendary anatomically shaped cork-latex footbed that conforms to your foot shape.',
        price: 110.00,
        discountPrice: 89.99,
        brand: 'Birkenstock',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=600&q=80',
        stock: 50,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'Converse Chuck Taylor All Star 70 High Top',
        description: 'Vintage canvas sneaker featuring heavier grade 12oz canvas, higher rubber foxing, and cushioned OrthoLite insole.',
        price: 90.00,
        discountPrice: 75.00,
        brand: 'Converse',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=600&q=80',
        stock: 65,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'Vans Old Skool Skate Shoes',
        description: 'Iconic low-top skate shoe featuring durable suede and canvas uppers, reinforced toe caps, and signature rubber waffle outsoles.',
        price: 70.00,
        discountPrice: 59.99,
        brand: 'Vans',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80',
        stock: 55,
        rating: 4.5,
        isFeatured: false,
      },
      {
        name: 'Salomon XT-6 Trail Running Shoes',
        description: 'Originally launched for ultra-distance races on harsh tracks, featuring Agile Chassis System and resistant TPU film.',
        price: 200.00,
        discountPrice: 179.99,
        brand: 'Salomon',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80',
        stock: 8, // Low stock
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'On Cloud 5 Lightweight Running Shoes',
        description: 'Zero-Gravity CloudTec cushioning for soft landings and explosive take-offs, patented speed-lacing system.',
        price: 140.00,
        discountPrice: 124.99,
        brand: 'On Running',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?auto=format&fit=crop&w=600&q=80',
        stock: 22,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'Timberland 6-Inch Premium Waterproof Boots',
        description: 'Classic rugged wheat leather boot with direct-attach seam-sealed waterproof construction and PrimaLoft insulation.',
        price: 210.00,
        discountPrice: 189.00,
        brand: 'Timberland',
        category: catMap['Shoes'],
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80',
        stock: 5, // Low stock
        rating: 4.9,
        isFeatured: false,
      },

      // Home & Kitchen (10)
      {
        name: 'Ninja AF101 4-Quart Air Fryer',
        description: 'Crisp and roast with up to 75% less fat than traditional frying methods, wide temperature range from 105°F to 400°F.',
        price: 119.99,
        discountPrice: 99.99,
        brand: 'Ninja',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80',
        stock: 35,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: 'Breville Barista Express Espresso Machine',
        description: 'Dose-controlled integrated conical burr grinder delivers optimal espresso extraction with commercial 54mm portafilter.',
        price: 699.95,
        discountPrice: 599.95,
        brand: 'Breville',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=600&q=80',
        stock: 12,
        rating: 4.9,
        isFeatured: true,
      },
      {
        name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 6 Qt',
        description: 'Replaces 7 appliances: pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and food warmer.',
        price: 99.95,
        discountPrice: 79.95,
        brand: 'Instant Pot',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
        stock: 40,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'KitchenAid Artisan Series 5-Quart Stand Mixer',
        description: 'Iconic tilt-head design with 10 speeds and 59-point planetary mixing action to easily knead, mix, and whip ingredients.',
        price: 449.99,
        discountPrice: 379.99,
        brand: 'KitchenAid',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?auto=format&fit=crop&w=600&q=80',
        stock: 15,
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'iRobot Roomba j7+ Self-Emptying Robot Vacuum',
        description: 'Identifies and avoids pet waste and charging cords with PrecisionVision Navigation, automatically empties for up to 60 days.',
        price: 799.99,
        discountPrice: 649.99,
        brand: 'iRobot',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=600&q=80',
        stock: 10,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: 'Vitamix 5200 Professional-Grade Blender',
        description: 'Variable speed control with aircraft-grade stainless steel blades capable of turning cold ingredients hot in 6 minutes.',
        price: 499.95,
        discountPrice: 429.95,
        brand: 'Vitamix',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=600&q=80',
        stock: 14,
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'Le Creuset Enameled Cast Iron Dutch Oven 5.5 Qt',
        description: 'Masterfully crafted French cast iron delivering superior heat distribution and retention with chip-resistant colorful enamel.',
        price: 420.00,
        discountPrice: 360.00,
        brand: 'Le Creuset',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1584990347449-397262c5b364?auto=format&fit=crop&w=600&q=80',
        stock: 7, // Low stock
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'Dyson V15 Detect Cordless Vacuum Cleaner',
        description: 'Laser reveals invisible dust on hard floors, intelligent piezo sensor measures and counts dust particles automatically.',
        price: 749.99,
        discountPrice: 649.99,
        brand: 'Dyson',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=600&q=80',
        stock: 16,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'Zwilling J.A. Henckels Pro 7-Piece Knife Block Set',
        description: 'Precision-forged from high-carbon German stainless steel with curved ergonomic bolster and triple-rivet handles.',
        price: 349.95,
        discountPrice: 299.95,
        brand: 'Zwilling',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=600&q=80',
        stock: 9, // Low stock
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'Fellow Stagg EKG Electric Gooseneck Pour-Over Kettle',
        description: 'Variable temperature control with precision pour spout, LCD screen, 60-minute temperature hold mode in Matte Black.',
        price: 165.00,
        discountPrice: 145.00,
        brand: 'Fellow',
        category: catMap['Home & Kitchen'],
        image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
        stock: 25,
        rating: 4.8,
        isFeatured: false,
      },

      // Books (10)
      {
        name: 'Atomic Habits by James Clear',
        description: 'An easy and proven way to build good habits and break bad ones, packed with actionable strategies from neuroscience and psychology.',
        price: 27.00,
        discountPrice: 16.99,
        brand: 'Penguin Random House',
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
        stock: 90,
        rating: 4.9,
        isFeatured: true,
      },
      {
        name: 'Clean Code: A Handbook of Agile Software Craftsmanship',
        description: 'Robert C. Martin presents a revolutionary paradigm with best practices of writing clean, maintainable, and readable code.',
        price: 54.99,
        discountPrice: 44.99,
        brand: 'Prentice Hall',
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80',
        stock: 45,
        rating: 4.8,
        isFeatured: true,
      },
      {
        name: 'Designing Data-Intensive Applications by Martin Kleppmann',
        description: 'The definitive guide to the architecture of distributed data storage, stream processing, consistency, and reliability.',
        price: 59.99,
        discountPrice: 48.99,
        brand: "O'Reilly Media",
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
        stock: 35,
        rating: 5.0,
        isFeatured: false,
      },
      {
        name: 'The Psychology of Money by Morgan Housel',
        description: 'Timeless lessons on wealth, greed, and happiness doing well with money is more about how you behave than what you know.',
        price: 19.99,
        discountPrice: 14.99,
        brand: 'Harriman House',
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80',
        stock: 60,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'Deep Work: Rules for Focused Success by Cal Newport',
        description: 'Master the superpower of deep, uninterrupted focus in a distracted world to produce elite results in less time.',
        price: 28.00,
        discountPrice: 19.99,
        brand: 'Grand Central',
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
        stock: 40,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'Thinking, Fast and Slow by Daniel Kahneman',
        description: 'Nobel laureate Daniel Kahneman takes us on a groundbreaking tour of the two systems that drive the way we think and decide.',
        price: 22.00,
        discountPrice: 15.99,
        brand: 'Farrar, Straus and Giroux',
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?auto=format&fit=crop&w=600&q=80',
        stock: 38,
        rating: 4.6,
        isFeatured: false,
      },
      {
        name: "JavaScript: The Definitive Guide 7th Edition",
        description: 'David Flanagan covers ECMAScript 2020, Node.js, and web platform APIs in this indispensable comprehensive programmer reference.',
        price: 69.99,
        discountPrice: 54.99,
        brand: "O'Reilly Media",
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
        stock: 30,
        rating: 4.8,
        isFeatured: false,
      },
      {
        name: 'Sapiens: A Brief History of Humankind by Yuval Noah Harari',
        description: 'Explore how an unexceptional ape became the ruler of planet Earth, bridging history and science to reconsider everything we know.',
        price: 24.99,
        discountPrice: 17.99,
        brand: 'Harper',
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80',
        stock: 55,
        rating: 4.7,
        isFeatured: false,
      },
      {
        name: 'System Design Interview – An Insider’s Guide by Alex Xu',
        description: 'Step-by-step framework to tackle large scale distributed system design interviews with clear diagrams and real-world questions.',
        price: 39.99,
        discountPrice: 32.99,
        brand: 'Independently Published',
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=80',
        stock: 7, // Low stock
        rating: 4.9,
        isFeatured: false,
      },
      {
        name: 'The Pragmatic Programmer: 20th Anniversary Edition',
        description: 'David Thomas and Andrew Hunt offer fresh modern insights into software craft, continuous learning, and pragmatic development.',
        price: 49.99,
        discountPrice: 39.99,
        brand: 'Addison-Wesley',
        category: catMap['Books'],
        image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80',
        stock: 4, // Low stock
        rating: 4.9,
        isFeatured: false,
      },
    ];

    const createdProducts = await Product.insertMany(rawProducts);

    // 4. Create 50 Realistic Reviews
    const reviewComments = [
      { rating: 5, comment: 'Absolutely outstanding product! Exceeded all my expectations.' },
      { rating: 5, comment: 'Exceptional build quality and works exactly as described. Highly recommended!' },
      { rating: 4, comment: 'Very good purchase overall. Great value for the price.' },
      { rating: 5, comment: 'I am thoroughly impressed by the performance and fast delivery.' },
      { rating: 4, comment: 'Solid quality, looks stylish and does its job flawlessly.' },
      { rating: 5, comment: 'One of the best purchases I have made this year. 10/10!' },
      { rating: 4, comment: 'Very reliable and easy to use. Would buy again.' },
      { rating: 3, comment: 'Decent product, but packaging could have been slightly better.' },
      { rating: 5, comment: 'Superb craftsmanship and fast checkout experience!' },
      { rating: 4, comment: 'Good quality material and very functional.' },
    ];

    const reviewsData = [];
    for (let i = 0; i < 50; i++) {
      const user = customers[i % customers.length];
      const product = createdProducts[i * 2 % createdProducts.length];
      const template = reviewComments[i % reviewComments.length];

      reviewsData.push({
        user: user._id,
        product: product._id,
        rating: template.rating,
        comment: template.comment,
        createdAt: new Date(Date.now() - (i + 1) * 24 * 60 * 60 * 1000),
      });
    }

    await Review.insertMany(reviewsData);

    // Update Product review counts and average ratings
    for (const product of createdProducts) {
      const pReviews = reviewsData.filter((r) => r.product.toString() === product._id.toString());
      if (pReviews.length > 0) {
        const avg = pReviews.reduce((acc, curr) => acc + curr.rating, 0) / pReviews.length;
        await Product.findByIdAndUpdate(product._id, {
          rating: Number(avg.toFixed(1)),
          numReviews: pReviews.length,
        });
      }
    }

    // 5. Create 20 Realistic Orders
    const orderStatuses = ['PLACED', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED'];
    const ordersData = [];

    for (let i = 0; i < 20; i++) {
      const customer = customers[i % customers.length];
      const p1 = createdProducts[(i * 3) % createdProducts.length];
      const p2 = createdProducts[(i * 3 + 1) % createdProducts.length];
      const status = orderStatuses[i % orderStatuses.length];

      const price1 = p1.discountPrice > 0 ? p1.discountPrice : p1.price;
      const price2 = p2.discountPrice > 0 ? p2.discountPrice : p2.price;
      const totalAmount = Number((price1 + price2 * 2).toFixed(2));

      ordersData.push({
        user: customer._id,
        products: [
          {
            product: p1._id,
            name: p1.name,
            image: p1.image,
            quantity: 1,
            price: price1,
          },
          {
            product: p2._id,
            name: p2.name,
            image: p2.image,
            quantity: 2,
            price: price2,
          },
        ],
        shippingAddress: {
          name: customer.name,
          phone: customer.phone,
          address: customer.address.address || '123 Main St',
          city: customer.address.city || 'Springfield',
          state: customer.address.state || 'IL',
          pincode: customer.address.pincode || '62701',
        },
        totalAmount,
        paymentMethod: 'COD',
        orderStatus: status,
        createdAt: new Date(Date.now() - (20 - i) * 2 * 24 * 60 * 60 * 1000),
      });
    }

    await Order.insertMany(ordersData);

    // Exact required output format
    console.log(`Categories: ${createdCategories.length}`);
    console.log(`Users: ${createdUsers.length}`);
    console.log(`Products: ${createdProducts.length}`);
    console.log(`Reviews: ${reviewsData.length}`);
    console.log(`Orders: ${ordersData.length}`);
    console.log('\nSeed completed successfully.');

    if (shouldExit) {
      process.exit(0);
    }
  } catch (error) {
    console.error('Error seeding database:', error);
    if (shouldExit) {
      process.exit(1);
    }
    throw error;
  }
};

module.exports = { seedDatabase: (shouldExit = false) => seedData(shouldExit) };

if (require.main === module) {
  seedData(true);
}

